export const SUBMITTING_ACCOUNT_INFO = 'SUBMITTING_ACCOUNT_INFO'
export const ACCOUNT_SIGN_IN = 'ACCOUNT_SIGN_IN'
export const ACCOUNT_SIGN_ERROR = 'ACCOUNT_SIGN_ERROR'
export const ACCOUNT_SIGN_OUT = 'ACCOUNT_SIGN_OUT'
